console.log("Ejercicio N°1");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("Girar a la izquierda");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
console.log("avanzar");
console.log("quitar");
